windows:
  - start: "01:00"
    end:   "08:00"
    bias:  "bullish"
  - start: "08:00"
    end:   "12:00"
    bias:  "neutral"
  - start: "12:00"
    end:   "17:00"
    bias:  "bullish"
  - start: "17:00"
    end:   "22:00"
    bias:  "bearish"
  - start: "22:00"
    end:   "01:00"
    bias:  "bearish"
