macro:
  gating_enabled: true
  scoring_enabled: true
confluence:
  tol_pct_min_5_15m: 0.0005
  tol_pct_min_1h_4h: 0.0003
  tol_atr_mult_5_15m: 0.15
  tol_atr_mult_1h_4h: 0.10
  ticksize_mult: 2
  weights:
    EMA20-1H: 10
    EMA50-15m: 8
    pivot-1H: 10
    BB-mid-15m: 6
    round-number: 6
    FVG-edge: 8
    SR-manual: 12
  score_cap: 15
